### ISSUE TITLE
Build a todo list using an object

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#379]
- [x]  store the todos array in an object

- [x]  have a displayTodos method

- [x]  have an addTodo method

- [x]  have a changeTodo method

- [x]  have a deleteTodo method
